### PR TITLE
Refactor connection list 

### PR DESCRIPTION
**Pull request by 16-karan**
## WHAT ##
- Shown connection list on sidebar
- Handled the responsiveness, dark and light mode.
- Handled the type errors

## WHY
- For the optimal user experience

## HOW
- Created the user friendly UI
- Implemented the back-end API to get the connection details

### CODE REVIEW

**Comment by sanjay-k1910** [comment]
@16-karan, When there is no connection data, can we show the below design instead of the current one?
Note: Ignore "Issue" button
Screenshot from 2023-10-27 17-49-12

**Comment by 16-karan** [comment]
@sanjay-k1910 @nishad-ayanworks @sunilbade I went through all flow of connections list, there are same message "Empty Data" that's why I kept this message, Should I update the message for all connections flow or keep as it is ?

**Comment by sanjay-k1910** [comment]
> @sanjay-k1910 @nishad-ayanworks @sunilbade I went through all flow of connections list, there are same message "Empty Data" that's why I kept this message, Should I update the message for all connections flow or keep as it is ?

As discussed with Nishad, Please implement the empty data component below for this page only as this PR is related to the connection list page.
Screenshot from 2023-10-27 18-55-19

**Comment by 16-karan** [comment]
> > @sanjay-k1910 @nishad-ayanworks @sunilbade I went through all flow of connections list, there are same message "Empty Data" that's why I kept this message, Should I update the message for all connections flow or keep as it is ?
> 
> As discussed with Nishad, Please implement the `EmptyListMessage` component below for this page only as this PR is related to the connection list page. Screenshot from 2023-10-27 18-55-19

@sanjay-k1910 @nishad-ayanworks  with reference to above, I have added  `EmptyListMessage` component.
Screenshot from 2023-10-27 19-49-41

**Review by sanjay-k1910 — APPROVED** [review]
LGTM

**Pull request merged**
